name: Deploy Spring Boot Microservice to AWS Lambda

on:
  push:
    branches: [ "master" ]   # runs on pushes to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   # N. Virginia region

    - name: Upload JAR to S3
      run: |
        aws s3 cp target/registry-0.0.1-SNAPSHOT.jar s3://myregistrybucket/

    - name: Update Lambda with new code
      run: |
        aws lambda update-function-code \
          --function-name registry-function \
          --s3-bucket myregistrybucket \
          --s3-key registry-0.0.1-SNAPSHOT.jar

